project_id = "kyvantdstjjdufpptqni"

[functions.admin-update-content]
verify_jwt = false

[functions.create-book-order]
verify_jwt = false

[functions.facebook-post]
verify_jwt = false

[functions.process-scheduled-posts]
verify_jwt = false

[functions.blog-admin]
verify_jwt = false

[functions.generate-ai-post]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.log-access-attempt]
verify_jwt = false

[functions.admin-otp]
verify_jwt = false
